# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Nexus_config = debug
  glfw_config = debug
  ImGui_config = debug
  Glad_config = debug
  Slicer_config = debug

else ifeq ($(config),release)
  Nexus_config = release
  glfw_config = release
  ImGui_config = release
  Glad_config = release
  Slicer_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := Nexus glfw ImGui Glad Slicer

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Nexus: glfw Glad ImGui
ifneq (,$(Nexus_config))
	@echo "==== Building Nexus ($(Nexus_config)) ===="
	@${MAKE} --no-print-directory -C vendor/Nexus -f Makefile config=$(Nexus_config)
endif

glfw:
ifneq (,$(glfw_config))
	@echo "==== Building glfw ($(glfw_config)) ===="
	@${MAKE} --no-print-directory -C vendor/Nexus/vendor/glfw -f Makefile config=$(glfw_config)
endif

ImGui:
ifneq (,$(ImGui_config))
	@echo "==== Building ImGui ($(ImGui_config)) ===="
	@${MAKE} --no-print-directory -C vendor/Nexus/vendor/ImGui -f Makefile config=$(ImGui_config)
endif

Glad:
ifneq (,$(Glad_config))
	@echo "==== Building Glad ($(Glad_config)) ===="
	@${MAKE} --no-print-directory -C vendor/Nexus/vendor/Glad -f Makefile config=$(Glad_config)
endif

Slicer: Nexus glfw Glad ImGui
ifneq (,$(Slicer_config))
	@echo "==== Building Slicer ($(Slicer_config)) ===="
	@${MAKE} --no-print-directory -C . -f Slicer.make config=$(Slicer_config)
endif

clean:
	@${MAKE} --no-print-directory -C vendor/Nexus -f Makefile clean
	@${MAKE} --no-print-directory -C vendor/Nexus/vendor/glfw -f Makefile clean
	@${MAKE} --no-print-directory -C vendor/Nexus/vendor/ImGui -f Makefile clean
	@${MAKE} --no-print-directory -C vendor/Nexus/vendor/Glad -f Makefile clean
	@${MAKE} --no-print-directory -C . -f Slicer.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Nexus"
	@echo "   glfw"
	@echo "   ImGui"
	@echo "   Glad"
	@echo "   Slicer"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"